/*
**  GSC-18128-1, "Core Flight Executive Version 6.7"
**
**  Copyright (c) 2006-2019 United States Government as represented by
**  the Administrator of the National Aeronautics and Space Administration.
**  All Rights Reserved.
**
**  Licensed under the Apache License, Version 2.0 (the "License");
**  you may not use this file except in compliance with the License.
**  You may obtain a copy of the License at
**
**    http://www.apache.org/licenses/LICENSE-2.0
**
**  Unless required by applicable law or agreed to in writing, software
**  distributed under the License is distributed on an "AS IS" BASIS,
**  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
**  See the License for the specific language governing permissions and
**  limitations under the License.
*/

/**
 * @file
 *
 * Purpose:
 *   This header file contains the Message Id's for messages used by the
 *   cFE core.
 *
 * Author:   R.McGraw/SSI
 *
 * Notes:
 *   This file should not contain messages defined by cFE external
 *   applications.
 *
 */

#ifndef COMMON_CFE_MSGIDS_H
#define COMMON_CFE_MSGIDS_H

/*
** Includes
*/

#include "cfe_mission_cfg.h"


#define CFE_PLATFORM_CMD_TOPICID_TO_MID(topic) (CFE_PLATFORM_CMD_MID_BASE + topic - CFE_MISSION_TELECOMMAND_BASE_TOPICID)
#define CFE_GLOBAL_CMD_TOPICID_TO_MID(topic)   (CFE_PLATFORM_CMD_MID_BASE_GLOB + topic - CFE_MISSION_TELECOMMAND_BASE_TOPICID)
#define CFE_PLATFORM_TLM_TOPICID_TO_MID(topic) (CFE_PLATFORM_TLM_MID_BASE + topic - CFE_MISSION_TELEMETRY_BASE_TOPICID)

/*
** cFE Command Message Id's
*/
#define CFE_EVS_CMD_MID         CFE_PLATFORM_CMD_TOPICID_TO_MID(CFE_MISSION_EVS_CMD_TOPICID)
#define CFE_TEST_CMD_MID        CFE_PLATFORM_CMD_TOPICID_TO_MID(CFE_MISSION_TEST_CMD_TOPICID)
#define CFE_SB_CMD_MID          CFE_PLATFORM_CMD_TOPICID_TO_MID(CFE_MISSION_SB_CMD_TOPICID)
#define CFE_TBL_CMD_MID         CFE_PLATFORM_CMD_TOPICID_TO_MID(CFE_MISSION_TBL_CMD_TOPICID)
#define CFE_TIME_CMD_MID        CFE_PLATFORM_CMD_TOPICID_TO_MID(CFE_MISSION_TIME_CMD_TOPICID)
#define CFE_ES_CMD_MID          CFE_PLATFORM_CMD_TOPICID_TO_MID(CFE_MISSION_ES_CMD_TOPICID)
#define CFE_EVS_SEND_HK_MID     CFE_PLATFORM_CMD_TOPICID_TO_MID(CFE_MISSION_EVS_SEND_HK_TOPICID)
#define CFE_SB_SEND_HK_MID      CFE_PLATFORM_CMD_TOPICID_TO_MID(CFE_MISSION_SB_SEND_HK_TOPICID)
#define CFE_TBL_SEND_HK_MID     CFE_PLATFORM_CMD_TOPICID_TO_MID(CFE_MISSION_TBL_SEND_HK_TOPICID)
#define CFE_TIME_SEND_HK_MID    CFE_PLATFORM_CMD_TOPICID_TO_MID(CFE_MISSION_TIME_SEND_HK_TOPICID)
#define CFE_ES_SEND_HK_MID      CFE_PLATFORM_CMD_TOPICID_TO_MID(CFE_MISSION_ES_SEND_HK_TOPICID)
#define CFE_SB_SUB_RPT_CTRL_MID CFE_PLATFORM_CMD_TOPICID_TO_MID(CFE_MISSION_SB_SUB_RPT_CTRL_TOPICID)
#define CFE_TIME_TONE_CMD_MID   CFE_PLATFORM_CMD_TOPICID_TO_MID(CFE_MISSION_TIME_TONE_CMD_TOPICID)
#define CFE_TIME_1HZ_CMD_MID    CFE_PLATFORM_CMD_TOPICID_TO_MID(CFE_MISSION_TIME_ONEHZ_CMD_TOPICID)

/*
** cFE Global Command Message Id's
*/
#define CFE_TIME_DATA_CMD_MID CFE_GLOBAL_CMD_TOPICID_TO_MID(CFE_MISSION_TIME_DATA_CMD_TOPICID)
#define CFE_TIME_SEND_CMD_MID CFE_GLOBAL_CMD_TOPICID_TO_MID(CFE_MISSION_TIME_SEND_CMD_TOPICID)

/*
** CFE Telemetry Message Id's
*/
#define CFE_ES_HK_TLM_MID           CFE_PLATFORM_TLM_TOPICID_TO_MID(CFE_MISSION_ES_HK_TLM_TOPICID)
#define CFE_EVS_HK_TLM_MID          CFE_PLATFORM_TLM_TOPICID_TO_MID(CFE_MISSION_EVS_HK_TLM_TOPICID)
#define CFE_TEST_HK_TLM_MID         CFE_PLATFORM_TLM_TOPICID_TO_MID(CFE_MISSION_TEST_HK_TLM_TOPICID)
#define CFE_SB_HK_TLM_MID           CFE_PLATFORM_TLM_TOPICID_TO_MID(CFE_MISSION_SB_HK_TLM_TOPICID)
#define CFE_TBL_HK_TLM_MID          CFE_PLATFORM_TLM_TOPICID_TO_MID(CFE_MISSION_TBL_HK_TLM_TOPICID)
#define CFE_TIME_HK_TLM_MID         CFE_PLATFORM_TLM_TOPICID_TO_MID(CFE_MISSION_TIME_HK_TLM_TOPICID)
#define CFE_TIME_DIAG_TLM_MID       CFE_PLATFORM_TLM_TOPICID_TO_MID(CFE_MISSION_TIME_DIAG_TLM_TOPICID)
#define CFE_EVS_LONG_EVENT_MSG_MID  CFE_PLATFORM_TLM_TOPICID_TO_MID(CFE_MISSION_EVS_LONG_EVENT_MSG_TOPICID)
#define CFE_EVS_SHORT_EVENT_MSG_MID CFE_PLATFORM_TLM_TOPICID_TO_MID(CFE_MISSION_EVS_SHORT_EVENT_MSG_TOPICID)
#define CFE_SB_STATS_TLM_MID        CFE_PLATFORM_TLM_TOPICID_TO_MID(CFE_MISSION_SB_STATS_TLM_TOPICID)
#define CFE_ES_APP_TLM_MID          CFE_PLATFORM_TLM_TOPICID_TO_MID(CFE_MISSION_ES_APP_TLM_TOPICID)
#define CFE_TBL_REG_TLM_MID         CFE_PLATFORM_TLM_TOPICID_TO_MID(CFE_MISSION_TBL_REG_TLM_TOPICID)
#define CFE_SB_ALLSUBS_TLM_MID      CFE_PLATFORM_TLM_TOPICID_TO_MID(CFE_MISSION_SB_ALLSUBS_TLM_TOPICID)
#define CFE_SB_ONESUB_TLM_MID       CFE_PLATFORM_TLM_TOPICID_TO_MID(CFE_MISSION_SB_ONESUB_TLM_TOPICID)
#define CFE_ES_MEMSTATS_TLM_MID     CFE_PLATFORM_TLM_TOPICID_TO_MID(CFE_MISSION_ES_MEMSTATS_TLM_TOPICID)

#endif /* CPU1_MSGIDS_H */
