# This mini-script runs at install time and generates a sample config file wrapper for lighttpd
# The wrapper just sets the "system_root" location for lighttpd to the UI install directory

FILE(TO_NATIVE_PATH "$ENV{DESTDIR}/${CMAKE_INSTALL_PREFIX}/ui" DESTDIR)
FILE(WRITE ${DESTDIR}/lighttpd-run.conf
    "# NOTE: This file is generated by the install script\n"
    "# It simply sets the lighttpd \"system_root\" variable to the of UI install directory\n"
    "var.system_root = \"${DESTDIR}\"\n"
    "var.http_port = 8080\n"
    "include system_root + \"/lighttpd.conf\"\n"
)

