name: Build COSMOS gem

# Run on all pull requests, and pushes in dev and main branches
on:
  push:
    branches:
      - dev
      - main
      - fix-cfs1022-test
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

# Force bash to apply pipefail option so pipeline failures aren't masked
defaults:
  run:
    shell: bash

env:
  COSMOS_VERSION: '6.10.5'
  GH_HOST: github.com
  GH_REPO: ${{ github.repository }}

jobs:
  stage-gem:
    strategy:
      fail-fast: false
      matrix:
        config: [ native_std ]

    name: 'Set up ${{ matrix.config }} gem source'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/core-flight-system/cfsbuildenv-linux
    steps:
      - name: Checkout Bundle
        uses: actions/checkout@v6
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare ${{ matrix.config }} Build
        run: make ${{ matrix.config }}.prep

      - name: Stage gem contents
        run: make ${{ matrix.config }}.gem

      - name: Upload gem contents
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.config }}-gem-source
          path: build-${{ matrix.config }}/cosmos/plugin/*


  build-gem:
    name: 'Build ${{ matrix.config }} gem binary'
    needs: stage-gem
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config: [ native_std ]

    env:
      GEM_WORKSPACE: ${{ github.workspace }}/build-gem-${{ matrix.config }}

    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v8
        with:
          name: ${{ matrix.config }}-gem-source
          path: ${{ env.GEM_WORKSPACE }}/source

      ## Note this does not use actions/checkout because this is a public repo
      - name: Check out COSMOS
        uses: actions/checkout@v6
        with:
          repository: 'OpenC3/cosmos-project'
          ref: 'v${{ env.COSMOS_VERSION }}'
          path: ${{ env.GEM_WORKSPACE }}/cosmos-project

      ## This needs to patch relative refs (e.g. "./") with absolute paths to remap them
      #- name: Set up COSMOS
      #  working-directory: ${{ env.GEM_WORKSPACE }}/cosmos-project
      #  run: sed -i -e 's/- ".\//- "$(realpath .)\//' ./compose.yaml

      - name: Build GEM
        working-directory: ${{ env.GEM_WORKSPACE }}/cosmos-project
        env:
          GEM_SOURCE_DIR: ${{ env.GEM_WORKSPACE }}/source
        run: >
          docker compose run --rm --no-deps
          -v ${GEM_SOURCE_DIR}:/openc3/local:z
          --user $(id -u):$(id -g)
          -w /openc3/local
          openc3-cosmos-cmd-tlm-api ruby /openc3/bin/openc3cli rake build VERSION=7.0.1

      - name: Upload gem binary
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.config }}-gem-binary
          path: ${{ env.GEM_WORKSPACE }}/source/*.gem
