name: Static Analysis

on:
  workflow_call:
    inputs:
      strict-dir-list:
        description: 'Directory List'
        type: string
        default: ''

# Force bash to apply pipefail option so pipeline failures aren't masked
defaults:
  run:
    shell: bash

jobs:
  #Checks for duplicate actions. Skips push actions if there is a matching or duplicate pull-request action. 
  check-for-duplicates:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
        should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content'
          skip_after_successful_duplicate: 'true'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  static-analysis:
    #Continue if check-for-duplicates found no duplicates. Always runs for pull-requests.
    needs: check-for-duplicates
    if: ${{ needs.check-for-duplicates.outputs.should_skip != 'true' }}
    name: Run cppcheck
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false

    steps:      
      - name: Install cppcheck
        run: sudo apt-get install cppcheck -y

        # Checks out a copy of the cfs bundle
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Run general cppcheck 
        run: |
          cppcheck --force --inline-suppr . --xml 2> general_cppcheck_err.xml  
          cppcheck --force --inline-suppr . 2> general_cppcheck_err.txt
          
      - name: Convert general cppcheck
        uses: airtower-luna/convert-to-sarif@v0.2.0
        with:
          tool: 'CppCheck'
          input_file: 'general_cppcheck_err.xml'
          sarif_file: 'general_cppcheck_err.sarif'
          
      - name: Define workspace
        run: |
          echo "CONTAINER_WORKSPACE=${PWD}" >> ${GITHUB_ENV}
          
      - name: Upload general SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'general_cppcheck_err.sarif'
          checkout_path: ${{ env.CONTAINER_WORKSPACE }}
          category: 'General-cppcheck'
          
        # Run strict static analysis for embedded portions of cfe, osal, and psp
      - name: Strict cppcheck
        if: ${{ inputs.strict-dir-list !='' }}
        run: |
          cppcheck --force --inline-suppr --std=c99 --language=c --enable=warning,performance,portability,style --suppress=variableScope --inconclusive ${{ inputs.strict-dir-list }} --xml 2> strict_cppcheck_err.xml 
          cppcheck --force --inline-suppr --std=c99 --language=c --enable=warning,performance,portability,style --suppress=variableScope --inconclusive ${{ inputs.strict-dir-list }} 2> strict_cppcheck_err.txt
 
      - name: Convert strict cppcheck
        uses: airtower-luna/convert-to-sarif@v0.2.0
        if: ${{ inputs.strict-dir-list !='' }}
        with:
          tool: 'CppCheck'
          input_file: 'strict_cppcheck_err.xml'
          sarif_file: 'strict_cppcheck_err.sarif'

      - name: Archive static analysis artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cppcheck-errors
          path: ./*cppcheck_err.*

      - name: Upload strict SARIF results
        uses: github/codeql-action/upload-sarif@v2
        if: ${{ inputs.strict-dir-list !='' }}
        with:
          sarif_file: 'strict_cppcheck_err.sarif'
          checkout_path: ${{ env.CONTAINER_WORKSPACE }}
          category: 'Strict-cppcheck'
  
      - name: Check for general errors
        run: |
          if [[ -s general_cppcheck_err.txt ]];
          then
            cat general_cppcheck_err.txt
            exit -1
          fi
      - name: Check for strict errors
        if: ${{ inputs.strict-dir-list !='' }}
        run: |
          if [[ -s strict_cppcheck_err.txt ]];
          then
            cat strict_cppcheck_err.txt
            exit -1
          fi
